### PR TITLE
adding manual examples as test files

### PR DESCRIPTION
**Pull request by cdwensley**
Manual examples 1,2,3,4,5 (section 1.9) and 1,2 (section 1.15) added as tst/example1.tst, ..., tst/example7.tst.  Also added tst/testall.g and tst/testing.g.  (Probably should have commented out the SetInfoLevel lines.)  Examples 4,5,7 fail to work correctly on my system.  Hopefully that is just here?

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Would be nice to see this together with Travis CI and CodeCov integration... I can help later.

**Comment by fingolfin** [comment]
Yes, having travis+codecov would be super helpful!

In the meantime, I run these tests with master, and it managed to trigger the AddressSanitizer, so there are some bugs out there in the C code which I now might be able to track down and squash.

**Comment by fingolfin** [comment]
Oops, didn't mean to commit that merge just yet, as it runs into errors... *sigh* stupid me

**Comment by cdwensley** [comment]
Well, for me no matter - I've pulled and deleted the branch. Still working on manual.

**Pull request merged**
